<?php

function doctor_menu()
{
    $items = array();
    
    $items['doctor']                     = array(
        'title' => t('Doctors'),
        'page callback' => 'doctors_list',
        'access arguments' => array(
            'access content'
        ),
        'type' => MENU_NORMAL_ITEM
    );
    $items['doctor/delete/%doctor_user'] = array(
        'title' => t('Delete doctor'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'doctor_delete_confirm',
            2
        ),
        'access arguments' => array(
            'access content'
        ),
        'type' => MENU_CALLBACK
    );
    $items['doctor/edit/%doctor_user']   = array(
        'title' => t('Edit Form'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'doctor_edit_confirm',
            2
        ),
        'access arguments' => array(
            'access content'
        ),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}
function doctors_list()
{
	global $base_path;
    $header = array(
        t('Doctor Name'),
        t('Gender'),
        t('Status'),
        t('Action')
    );
	$str = '';
    
	$query = db_select('doctor', 'f');
	$query->fields('f');
		 
	$arr_result = $query->execute();
	
	$rows = array();
	foreach($arr_result as $result) {
		$gender = $result->gender;
            $status = $result->status;
            $row[]  = array(
                stripslashes(ucwords($result->firstname)) . ' ' . stripslashes(ucwords($result->lastname)),
                $gender,
                $status,
                "<a href=".$base_path."doctor/edit/{$result->doctorid}>" . t('Edit') . "</a> | <a href=".$base_path."doctor/delete/{$result->doctorid}>" . t('Delete') . "</a>"
            );
		
	}
	
	$attributes = null;
	$str.=theme('table', array(
	  'header' => $header,
	  'rows' => $row
	));
    return $str;
}
function doctor_user_load($doctorid)
{
    
    $query = "SELECT * FROM {doctor} WHERE doctorid = 1";
    $rs    = db_query($query);
    
    if ($rs) {
        while ($data = db_fetch_object($rs)) {
            return $data;
        }
    }
    return FALSE;
}
function doctor_delete_confirm($form, &$form_state, $doctor)
{
    $form['_doctor'] = array(
        '#type' => 'value',
        '#value' => $doctor
    );
    
    return confirm_form($form, t('Are you sure you want to delete this doctor?'), isset($_GET['destination']) ? $_GET['destination'] : "doctor", t('This action cannot be undone.'), t('Delete'), t('Cancel'));
}

function doctor_delete_confirm_submit($form, &$form_state)
{
    $form_values = $form_state['values'];


    if ($form_state['values']['confirm']) {
        $doctor = $form_state['values']['_doctor'];
		$doctorId = $doctor->doctorid;
        $query = "DELETE  FROM {doctor} where doctorid=".$doctorId;
        $rs    = db_query($query);
        drupal_set_message(t('Doctor has been deleted successfully.'));
    }
    drupal_goto("doctor");
}
function doctor_edit_confirm($form, &$form_state, $doctor)
{
    $form['_doctor']   = array(
        '#type' => 'value',
        '#value' => $doctor
    );
    $form['firstname'] = array(
        '#title' => t('First Name'),
        '#type' => 'textfield',
		'#default_value' => $form_state['build_info']['args'][0]->firstname
    );
    $form['lastname']  = array(
        '#title' => t('Last Name'),
        '#type' => 'textfield'
    );
    $form['gender']    = array(
        '#title' => t('Gender'),
        '#type' => 'radios',
        '#options' => array(
            t('male'),
            t('female')
        )
    );
    $form['status']    = array(
        '#title' => t('Status'),
        '#type' => 'radios',
        '#default_value' => 'active',
        '#options' => array(
            t('active'),
            t('inactive')
        )
    );
    return confirm_form($form, t(''), isset($_GET['destination']) ? $_GET['destination'] : "doctor", t(''), t('Edit'), t('Cancel'));
}


function doctor_edit_confirm_submit($form, &$form_state)
{
    if ($form_state['values']['confirm']) {
        $doctor    = $form_state['values']['_doctor'];
		
        $firstname = $form_state['values']['firstname'];
        $lastname  = $form_state['values']['lastname'];
        $gender1   = $form_state['values']['gender'];
        $gender    = $gender1 ? t('female') : t('male');
        $status1   = $form_state['values']['status'];
        $status    = $status1 ? t('inactive') : t('active');
        $query     = "UPDATE  {doctor} SET firstname = '$firstname', lastname= '$lastname', gender = '$gender', status = '$status'  WHERE  doctorid=$doctor->doctorid";
        $rs        = db_query($query);
        $rs        = db_query($query);
    }
    drupal_goto("doctor");
}

function db_fetch_object($res)
{
    return $res->fetchObject();
}

